### ISSUE TITLE
 custom windows authentication pop up

### ISSUE THREAD

**Issue by gamerenzz** [Visigo/SharePointFBAPack#172]
https://dpcrew.wordpress.com/2015/04/16/custom-sign-in-page-for-sharepoint-2010-claims-authentication-in-windows-authentication-mode/amp/

not support sharepoint 2013

Excuse me,stand by sharepoint 2013 ？

Please forgive me, English is translated by Google，

**Comment by ccoulson** [comment]
The FBA Pack does support SharePoint 2013.  However the FBA Pack doesn't have anything to do with the login page - you still use SharePoint's built in login page (which can be customized).  Instead of following the instructions on that page for customizing the login page, I suggest you take a copy of the login page included with SharePoint and customize that.  There's a few details here:
https://stackoverflow.com/questions/19793696/custom-login-page-in-sharepoint-2013-with-fba-autentication#:~:text=1%20Answer&text=The%20deafult%20login%20page%20is,modify%20that%20in%20Visual%20Studio.
